import logging

import google.generativeai as genai
from users.serializers import HairdresserFullInfoSerializer
from users.models import Hairdresser
from django.http import JsonResponse
from django.conf import settings
from preferences.models import Preferences
from preferences.serializers import PreferencesNameSerializer
from hairmatch.problems import Problem, body_error, is_id_list, validation_problem

logger = logging.getLogger(__name__)

def setup_environment():
    gemini_api_key = settings.GEMINI_API_KEY 
    if not gemini_api_key:
        raise ValueError("GEMINI_API_KEY not defined")
    genai.configure(api_key=gemini_api_key)

def load_hairdresser_data(hairdresser_id: int): 
    try: 
        hairdresser = Hairdresser.objects.get(id=hairdresser_id)
    except Hairdresser.DoesNotExist:
        return None
    hairdresser_serialized = HairdresserFullInfoSerializer(hairdresser).data
    return hairdresser_serialized


def generate_ai_text(prompt, model_name='gemini-2.0-flash', temperature=0.7, max_output_tokens=200):
    """
    Generates text using Google's generative model.

    Args:
        prompt (str): The prompt for the model.
        model_name (str): The name of the model to use.
        temperature (float): The temperature for the generation.
        max_output_tokens (int): The maximum number of tokens in the output.

    Returns:
        str: The text generated by the model.
    """
    model = genai.GenerativeModel(model_name)
    response = model.generate_content(
        prompt,
        generation_config={
            "temperature": temperature,
            "max_output_tokens": max_output_tokens
        }
    )
    return response.text

def process_hairdresser_profile(profile_data):
    """
    Processes a hairdresser's profile to generate a summarized description.

    Args:
        profile_data (dict): A dictionary containing the hairdresser's profile data.

    Returns:
        str: A summarized and attractive description of the profile.
    """
    
    prompt1 = (
        "Analise o perfil a seguir e destaque as informações mais relevantes que "
        "ajudariam um cliente a decidir se deve escolher este cabeleireiro. "
        "Considere aspectos como especializações, experiência, avaliações, "
        f"localização, entre outros.\n\nDados do perfil do cabeleireiro:\n{profile_data}"
    )
    relevant_information = generate_ai_text(prompt1)

    prompt2 = (
        "Com base nas informações mais relevantes identificadas abaixo, elabore um "
        "resumo claro e atrativo do perfil do cabeleireiro, em apenas um parágrafo, "
        "destacando seus principais diferenciais para potenciais clientes.\n\n"
        f"Informações relevantes sobre o cabeleireiro:\n{relevant_information}"
    )
    final_description = generate_ai_text(prompt2, max_output_tokens=100)
    return final_description

def hairdresser_profile_ai_completion(data):
    """
    Generates the description for the profile in `data`. Raises Problem: 400 validation-error for
    `preferences` that is not a list of ids, 503 ai-service-unavailable when Gemini is not configured or fails.
    """
    preferences_ids = data.get('preferences')
    if not is_id_list(preferences_ids):
        raise validation_problem([body_error('preferences', 'The preferences must be a list of ids.')])

    try:
        setup_environment()
        serialized_preferences = PreferencesNameSerializer(
            Preferences.objects.filter(id__in=preferences_ids),
            many=True).data

        hairdresser_data = data
        hairdresser_data['preferences'] = serialized_preferences

        generated_description = process_hairdresser_profile(hairdresser_data)
    except Exception:
        logger.exception('Gemini completion failed')
        raise Problem('ai-service-unavailable', 'The description could not be generated right now. Try again.')
    return JsonResponse({'result': generated_description}, status=200)
