"""
Django settings for hairmatch project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
import sys

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-b$7)-^_%c!#6^bsob1w^c*hz1ie&3*bny&(on%2%0=+0sm53%h'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

S3_BUCKET_NAME = os.getenv('S3_BUCKET_NAME')
# Host used in media URLs returned to clients; the backend itself talks to S3 via AWS_ENDPOINT_URL.
S3_PUBLIC_ENDPOINT_URL = os.getenv('S3_PUBLIC_ENDPOINT_URL', os.getenv('AWS_ENDPOINT_URL'))
BACKEND_ALLOWED_HOST = os.getenv('BACKEND_ALLOWED_HOST')
BACKEND_ALLOWED_CORS = os.getenv('BACKEND_ALLOWED_CORS')
GEMINI_API_KEY = os.getenv('GEMINI_API_KEY')
EVOLUTION_API_URL=os.getenv('EVOLUTION_API_URL')
EVOLUTION_API_KEY=os.getenv('EVOLUTION_API_KEY')
EVOLUTION_INSTANCE_NAME=os.getenv('EVOLUTION_INSTANCE_NAME')
# Cognito user pool and app client. Empty in dev: the backend looks them up by name (hairmatch-dev / hairmatch-backend).
COGNITO_USER_POOL_ID = os.getenv('COGNITO_USER_POOL_ID', '')
COGNITO_APP_CLIENT_ID = os.getenv('COGNITO_APP_CLIENT_ID', '')
# Tests use an in-memory Cognito so they need no emulator.
COGNITO_USE_FAKE = 'test' in sys.argv
TEST_RUNNER = 'hairmatch.test_runner.HairmatchTestRunner'
# Base of every problem `type` (RFC 9457). A fixed URI, not an env var; it need not resolve.
PROBLEM_TYPE_BASE_URI = 'https://hairmatch.app/problems/'
GOOGLE_OAUTH_CLIENT_IDS = [
    client_id.strip()
    for client_id in os.getenv('GOOGLE_OAUTH_CLIENT_IDS', '').split(',')
    if client_id.strip()
]

# Application definition

INSTALLED_APPS = [
    'users',
    'preferences',
    'review',
    'availability',
    'service',
    'reserve',
    'agenda',
    'chatbot',
    'rest_framework',
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'hairmatch.problems.ProblemDetailsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'hairmatch.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'hairmatch.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': '5432', 
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Media files live in S3; tests use an in-memory storage so they need no bucket.
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.InMemoryStorage'
        if 'test' in sys.argv
        else 'hairmatch.storage.S3MediaStorage',
    },
    'staticfiles': {
        'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage',
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

ALLOWED_HOSTS = [
    BACKEND_ALLOWED_HOST,
    'localhost',
    '127.0.0.1',
]

CORS_ALLOWED_ORIGINS = [
    'http://localhost:8081',
    BACKEND_ALLOWED_CORS,
    'http://localhost:8000'
]
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:8081',
    BACKEND_ALLOWED_CORS,
    'http://localhost:8000'
]
CORS_ALLOW_CREDENTIALS=True
AUTH_USER_MODEL = 'users.User'

CORS_ALLOW_METHODS = [
    'GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS'
]

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    "ngrok-skip-browser-warning"
]

REST_FRAMEWORK = {
    'EXCEPTION_HANDLER': 'hairmatch.problems.exception_handler',
    # Proxies in front of Django. 0 identifies a client by REMOTE_ADDR alone; without it DRF would trust
    # an X-Forwarded-For sent by the client and the throttles could be dodged by changing that header.
    'NUM_PROXIES': int(os.getenv('BACKEND_NUM_PROXIES', '0')),
}
