export interface Customer {
    first_name: string, 
    last_name: string, 
    email: string, 
    password: string,
    phone: string,
    state: string,
    complement?: string,
    neighborhood: string,
    address: string,
    number?: string,
    postal_code: string,
    rating: number,
    role: string,
    cpf: string,
}