# Generated by Django 4.2.20 on 2026-09-29 18:40

from django.db import migrations
import hairmatch.images


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='picture',
            field=hairmatch.images.WebPImageField(blank=True, null=True, upload_to='reviews/images/'),
        ),
    ]
