# Generated by Django 5.2.17 on 2026-10-10 15:39

import django.db.models.deletion
import hairmatch.images
import review.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_customerrating'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', hairmatch.images.WebPImageField(upload_to=review.models.review_picture_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='review.review')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
