# Generated by Django 5.2.17 on 2026-10-10 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_reviewpicture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='picture',
        ),
    ]
