# Generated by Django 4.2.20 on 2026-09-29 18:37

from django.db import migrations
import hairmatch.images
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=hairmatch.images.WebPImageField(blank=True, null=True, upload_to=users.models.user_profile_picture_path),
        ),
    ]
