# Generated by Django 5.2.17 on 2026-10-10 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_create_cache_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rating',
            field=models.FloatField(blank=True, default=5, null=True),
        ),
    ]
