# Generated by Django 5.2.17 on 2026-10-10 15:40

import django.db.models.deletion
import hairmatch.images
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_null_customer_ratings'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', hairmatch.images.WebPImageField(upload_to=users.models.gallery_photo_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hairdresser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_photos', to='users.hairdresser')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['hairdresser', '-created_at'], name='gallery_hairdresser_created')],
            },
        ),
    ]
