name: Run Hairmatch Backend Unit Tests

on:
  push:
    branches:
      - feature/cruds_of_er_models-12
      - develop
      - main
  pull_request:
    branches:
      - feature/cruds_of_er_models-12
      - develop
      - main

jobs:
  test:
    name: Django Tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: hairmatch_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DB_HOST: localhost
      DB_NAME: hairmatch_db
      DB_USER: postgres
      DB_PASSWORD: postgres

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        working-directory: ./backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run migrations
        working-directory: ./backend
        run: python manage.py migrate

      - name: Run tests
        working-directory: ./backend
        run: coverage run manage.py test
      
      - name: Run tests coverage report
        working-directory: ./backend
        run: coverage report -m
